import {
  SiAngular,
  SiCplusplus,
  SiCss,
  SiDotnet,
  SiGit,
  SiGithubactions,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiOpenjdk,
  SiPython,
  SiReact,
  SiTypescript,
} from 'react-icons/si';
import {
  TbApi,
  TbBinaryTree,
  TbBrain,
  TbBrandCSharp,
  TbBrandDocker,
  TbBuildingBridge2,
  TbCircleCheck,
  TbCircleX,
  TbClockCog,
  TbCloud,
  TbComponents,
  TbCube,
  TbDatabase,
  TbDatabaseCog,
  TbFileAnalytics,
  TbFileTypePdf,
  TbInfinity,
  TbLayoutList,
  TbListCheck,
  TbListDetails,
  TbPlugConnected,
  TbPuzzle,
  TbRefresh,
  TbRobot,
  TbRobotFace,
  TbRocket,
  TbSitemap,
  TbSparkles,
  TbSql,
  TbTestPipe,
  TbWorldSearch,
} from 'react-icons/tb';
import { DiMsqlServer } from 'react-icons/di';

const ICONS = {
  SiAngular,
  SiCplusplus,
  SiCss,
  SiDotnet,
  SiGit,
  SiGithubactions,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiOpenjdk,
  SiPython,
  SiReact,
  SiTypescript,
  TbApi,
  TbBinaryTree,
  TbBrain,
  TbBrandCSharp,
  TbBrandDocker,
  TbBuildingBridge2,
  TbCircleCheck,
  TbCircleX,
  TbClockCog,
  TbCloud,
  TbComponents,
  TbCube,
  TbDatabase,
  TbDatabaseCog,
  TbFileAnalytics,
  TbFileTypePdf,
  TbInfinity,
  TbLayoutList,
  TbListCheck,
  TbListDetails,
  TbPlugConnected,
  TbPuzzle,
  TbRefresh,
  TbRobot,
  TbRobotFace,
  TbRocket,
  TbSitemap,
  TbSparkles,
  TbSql,
  TbTestPipe,
  TbWorldSearch,
  DiMsqlServer,
};

export function resolveIcon(name) {
  if (!name || typeof name !== 'string') return null;
  return ICONS[name] || null;
}
